name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.2.11
authors:
  - Hurshi <ihsruh@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.1+1
  dio: ^3.0.1
  json_annotation: ^3.0.0
  json_serializable: ^3.0.0
  path: ^1.7.0
  path_provider: ^1.6.18
  quiver: ^2.0.3
  sqflite: ^1.1.6+3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.6

flutter:
  module:
    androidX: true
